import os
SIAT_LIB_VERSION = '1.0.4'
SB_DS = os.sep
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
TMP_DIR = BASE_DIR + SB_DS + 'temp'

MOD_ELECTRONICA_ENLINEA = 1;
MOD_COMPUTARIZADA_ENLINEA = 2;
MOD_PORTAL_WEB = 3;

TIPO_EMISION_ONLINE = 1;
TIPO_EMISION_OFFLINE = 2;
TIPO_EMISION_MASIVA = 3;

TIPO_FACTURA_CREDITO_FISCAL = 1;
TIPO_FACTURA_SIN_CREDITO_FISCAL = 2;
TIPO_FACTURA_AJUSTE = 3;

AMBIENTE_PRODUCCION = 1;
AMBIENTE_PRUEBAS = 2;
DATETIME_FORMAT = '%Y-%m-%dT%H:%M:%S.%f'

class TiposDocumentoSector:
	FACTURA_COMPRA_VENTA = 1
	FACTURA_ALQUILER_INMUEBLES = 2
	FACTURA_COMERCIAL_EXPORTACION = 3
	FACTURA_COMERCIAL_EXPORTACION_LIBRA_CONSIGNACION = 4
	FACTURA_VENTA_ZONA_FRANCA = 5
	FACTURA_SERVICIO_TURISTICO = 6
	FACTURA_SEG_ALIMENTARIA = 7
	FACTURA_TASA_CERO_LIBROS = 8
	FACTURA_COMPRA_VENTA_MONEDA_EXTRAJERA = 9
	FACTURA_DUTTY_FREE = 10
	FACTURA_SECTOR_EDUCATIVO = 11
	FACTURA_COM_HIDROCARBUROS = 12
	FACTURA_SERV_BASICOS = 13
	FACTURA_PRODS_ICE = 14
	FACTURA_ENT_FINANCIERA = 15
	FACTURA_HOTELES = 16
	FACTURA_HOSPITALES = 17
	FACTURA_JUEGOS_AZAR = 18
	FACTURA_HIDROCARBUROS = 19
	FACTURA_EXPORT_MINERALES = 20
	FACTURA_VENTA_MINERALES = 21
	FACTURA_TELECOMUNICACIONES = 22
	FACTURA_PREVALORADA = 23
	FACTURA_NOTA_CRED_DEB = 24
	FACTURA_COM_EXPORT_SERVICIOS = 28
	FACTURA_NOTA_CONCILIACION = 29
	FACTURA_BOLETO_AEREO = 30
	FACTURA_SUMIN_ENERGIA = 31
	FACTURA_ICE_ZONA_FRANCA = 32 
